model_type: random_forest
random_state: 42

test_size: 0.2
validation_size: 0.1
min_samples: 1000
feature_selection: true
scaling: true

hyperparameters:
  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, 30, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ['auto', 'sqrt']
    class_weight: ['balanced', 'balanced_subsample']
  
  gradient_boosting:
    n_estimators: [100, 200, 300]
    learning_rate: [0.01, 0.1, 0.3]
    max_depth: [3, 5, 7]
    min_samples_split: [2, 5]
    subsample: [0.8, 1.0]
    
  xgboost:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.3]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]
    min_child_weight: [1, 3, 5]

features:
  transaction_patterns:
    enabled: true
    window_sizes: [10, 20, 50]
    
  temporal_patterns:
    enabled: true
    time_windows: ['1h', '6h', '24h', '7d']
    
  network_metrics:
    enabled: true
    max_depth: 3
    
  amount_patterns:
    enabled: true
    quantiles: [0.25, 0.5, 0.75, 0.9, 0.95]

cv_folds: 5
cv_scoring:
  - accuracy
  - precision
  - recall
  - f1
  - roc_auc

early_stopping:
  enabled: true
  patience: 5
  min_delta: 0.001
  monitor: val_loss

min_performance:
  accuracy: 0.75
  precision: 0.7
  recall: 0.7
  f1_score: 0.7

output:
  save_model: true
  save_metrics: true
  save_predictions: true
  save_feature_importance: true
  model_format: joblib

logging:
  level: INFO
  save_to_file: true
  log_file: logs/training.log

parallel_jobs: -1
memory_limit: null
gpu_enabled: false

class_balancing:
  enabled: true
  method: smote
  sampling_strategy: auto

feature_importance:
  enabled: true
  methods:
    - permutation
    - shap
    - gain

outlier_detection:
  enabled: true
  contamination: 0.1
  methods:
    - isolation_forest
    - local_outlier_factor

labels:
  fa:
    suspicious: "مشکوک"
    normal: "عادی"
    high_risk: "ریسک بالا"
    medium_risk: "ریسک متوسط"
    low_risk: "ریسک پایین"
  en:
    suspicious: "Suspicious"
    normal: "Normal"
    high_risk: "High Risk"
    medium_risk: "Medium Risk"
    low_risk: "Low Risk"
